n1 = int (input ('Digite um valor: '))
n2 = int (input ('Digite outro valor: '))
print (f'A soma é {n1 + n2}, a subtração é {n1 - n2}, a multiplicação é {n1 * n2}')
print (f'A exponenciação é {n1 ** n2}, a divisão é {n1 / n2 :.3f}')
print (f'A divisão inteira é {n1 // n2 :.3f} e o resto é {n1 % n2}')
