n1 = int (input ('Digite um valor: '))
n2 = int (input ('Digite outro valor: '))
print (f'A soma dos valores vale {n1 + n2}' )
print (f'A subtração dos valores vale {n1 - n2}')
print (f'A multiplicação dos valores vale {n1 * n2}')
print (f'A exponenciação dos valores vale {n1 ** n2}')
print (f'A divisão dos valores vale {n1 / n2 :.3f}')
print (f'A divisão inteira dos valores vale {n1 // n2 :.3f}')
print (f'O resto da divisão é {n1 % n2}')
