n = int(input('Digite um inteiro: '))
n1 = input ('Digite alguma coisa: ')
n2 = input('Digite outra coisa: ')
n3 = float (input('Digite um número: '))
print(n)
print(n1.isalpha())
print(type (n2))
print (n3.is_integer())